import LatticePathOrders.MatrixBounds
import Mathlib.Data.ZMod.Basic

/-!
# The six parity matrices generated by the two adjacency blocks

This is the exact two-by-two calculation over `ZMod 2` used in the endpoint
parity theorem.  It is kept independent of rational-Dyck paths.
-/

namespace LatticePathOrdersClassical

abbrev F2 := ZMod 2

@[ext]
structure F2Matrix where
  a11 : F2
  a12 : F2
  a21 : F2
  a22 : F2
deriving DecidableEq

namespace F2Matrix

def one : F2Matrix := ⟨1, 0, 0, 1⟩

def mul (left right : F2Matrix) : F2Matrix :=
  ⟨left.a11 * right.a11 + left.a12 * right.a21,
   left.a11 * right.a12 + left.a12 * right.a22,
   left.a21 * right.a11 + left.a22 * right.a21,
   left.a21 * right.a12 + left.a22 * right.a22⟩

instance : One F2Matrix := ⟨one⟩
instance : Mul F2Matrix := ⟨mul⟩

@[simp] theorem one_mul (matrix : F2Matrix) : 1 * matrix = matrix := by
  change mul one matrix = matrix
  ext <;> simp [one, mul]

@[simp] theorem mul_one (matrix : F2Matrix) : matrix * 1 = matrix := by
  change mul matrix one = matrix
  ext <;> simp [one, mul]

theorem mul_assoc (left middle right : F2Matrix) :
    (left * middle) * right = left * (middle * right) := by
  change mul (mul left middle) right = mul left (mul middle right)
  ext <;> simp [mul] <;> ring

def ofNatMatrix (matrix : LatticePathOrders.Mat2) : F2Matrix :=
  ⟨matrix.a11, matrix.a12, matrix.a21, matrix.a22⟩

theorem ofNatMatrix_mul (left right : LatticePathOrders.Mat2) :
    ofNatMatrix (left * right) = ofNatMatrix left * ofNatMatrix right := by
  change ofNatMatrix (left * right) = mul (ofNatMatrix left) (ofNatMatrix right)
  ext <;> simp [ofNatMatrix, mul, LatticePathOrders.Mat2.mul]

@[simp] theorem ofNatMatrix_one :
    ofNatMatrix (1 : LatticePathOrders.Mat2) = 1 := rfl

def F : F2Matrix := ofNatMatrix (LatticePathOrders.T 1)
def S : F2Matrix := ofNatMatrix (LatticePathOrders.T 2)

def fPow (exponent : Nat) : F2Matrix :=
  match exponent % 3 with
  | 0 => 1
  | 1 => F
  | _ => F * F

theorem F_sq : F * F = ofNatMatrix LatticePathOrders.E := by
  decide

theorem S_eq_D : S = ofNatMatrix LatticePathOrders.D := by
  decide

@[simp] theorem fPow_zero : fPow 0 = 1 := rfl

theorem fPow_mod (exponent : Nat) : fPow (exponent % 3) = fPow exponent := by
  unfold fPow
  rw [Nat.mod_mod]

theorem fPow_eq_of_mod_eq {left right : Nat}
    (h : left % 3 = right % 3) : fPow left = fPow right := by
  rw [← fPow_mod left, ← fPow_mod right, h]

theorem fPow_add (left right : Nat) :
    fPow (left + right) = fPow left * fPow right := by
  unfold fPow
  have hleft : left % 3 = 0 ∨ left % 3 = 1 ∨ left % 3 = 2 := by omega
  have hright : right % 3 = 0 ∨ right % 3 = 1 ∨ right % 3 = 2 := by omega
  rcases hleft with hleft | hleft | hleft <;>
    rcases hright with hright | hright | hright <;>
    simp [Nat.add_mod, hleft, hright, F] <;> decide

theorem fPow_three : fPow 3 = 1 := by decide

theorem fPow_mul_S_fPow (left right : Nat) :
    fPow left * S * fPow right =
      fPow (left + 3 - (right % 3)) * S := by
  have hleft : left % 3 = 0 ∨ left % 3 = 1 ∨ left % 3 = 2 := by omega
  have hright : right % 3 = 0 ∨ right % 3 = 1 ∨ right % 3 = 2 := by omega
  rcases hleft with hleft | hleft | hleft <;>
    rcases hright with hright | hright | hright <;>
    simp [fPow, hleft, hright, Nat.add_mod, S, F] <;>
    ext <;> decide

theorem S_mul_fPow_mul_S (exponent : Nat) :
    S * fPow exponent * S = fPow (3 - (exponent % 3)) := by
  have h : exponent % 3 = 0 ∨ exponent % 3 = 1 ∨ exponent % 3 = 2 := by omega
  rcases h with h | h | h <;>
    simp [fPow, h, S, F] <;>
    ext <;> decide

theorem S_mul_fPow (exponent : Nat) :
    S * fPow exponent = fPow (3 - (exponent % 3)) * S := by
  simpa using fPow_mul_S_fPow 0 exponent

end F2Matrix

end LatticePathOrdersClassical
